<div class="container mission">
	<h3 class="blue-gradient mission" title="Terms of Service"><span>Terms of Service</span></h3>
	</div>

<div id="mainContent">
<div class="Section_A">
	<div class="Section_AB_1">
		<div class="Section_A_Text" >
		
	PLEASE READ THIS TERMS OF USE AGREEMENT (THE “AGREEMENT”) CAREFULLY. THIS IS A BINDING, CONTRACTUAL AGREEMENT BETWEEN YOU AND ATLAS POWERED, LLC, ITS AFFILIATES OR AGENTS (“ATLAS”) AND APPLIES TO YOUR USE OF (I) ANY OF ATLAS’ PROPRIETARY SOFTWARE APPLICATIONS FOR MOBILE DEVICES, INCLUDING ATLAS DIRECT, ATLAS AND ATLAS PRO, INCLUDING ALL ENHANCEMENTS, VERSIONS, AND MODIFICATIONS TO THE FOREGOING (EACH, AN “APPLICATION”); AND (II) THE SERVICES PROVIDED BY ATLAS THROUGH THE APPLICATION AND/OR ANY ATLAS WEBSITE (SUCH WEBSITE, THE “WEBSITE” AND THE PROVISION OF THE APPLICATION AND RELATED SERVICES, THE “SERVICES”)
BY ACCESSING OR USING THIS WEBSITE, THE SOFTWARE, THE WIDGET, THE SERVICES OR APPLICATION, CLICKING ON THE “I ACCEPT” BUTTON, COMPLETING THE REGISTRATION PROCESS, AND/OR MERELY BROWSING THE WEBSITE, YOU REPRESENT THAT (1) YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THIS AGREEMENT, (2) YOU ARE OF LEGAL AGE TO FORM A BINDING CONTRACT WITH ATLAS, AND (3) YOU HAVE THE AUTHORITY TO ENTER INTO THIS AGREEMENT PERSONALLY OR ON BEHALF OF THE COMPANY YOU HAVE NAMED AS THE CUSTOMER, AND TO BIND THAT COMPANY TO THESE TERMS.  THE TERM “YOU” REFERS TO THE INDIVIDUAL OR LEGAL ENTITY, AS APPLICABLE, IDENTIFIED AS THE CUSTOMER WHEN YOU REGISTERED ON THE WEBSITE.  IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, YOU MAY NOT ACCESS OR USE THIS WEBSITE OR THE SERVICES. 
IF YOU SUBSCRIBE TO THE SERVICES FOR A TERM (THE “INITIAL TERM”), THEN THE TERMS WILL BE AUTOMATICALLY RENEWED FOR ADDITIONAL PERIODS OF THE SAME DURATION AS THE INITIAL TERM AT COMPANY’S THEN-CURRENT FEE FOR SUCH SERVICES UNLESS YOU DECLINE TO RENEW YOUR SUBSCRIPTION IN ACCORDANCE WITH SECTION 9.6 BELOW.
THE TERMS OF USE REQUIRE THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS, AND ALSO LIMIT THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF A DISPUTE.
Your use of, and participation in, certain Services may be subject to additional terms (“Supplemental Terms”) and such Supplemental Terms will either be listed in these Terms of Use or will be presented to you for your acceptance when you sign up to use the supplemental Service. If these Terms of Use are inconsistent with such Supplemental Terms, the Supplemental Terms shall control with respect to such Service.  These Terms of Use and any applicable Supplemental Terms are referred to herein as the “Terms.” 
Some of the features and functions of the Services are limited to users of Atlas Direct service and Application. You must be affiliated with a customer of Atlas Direct to have access to such features. 

Atlas knows that your privacy is important. For this reason, we have created a privacy policy that describes our collection, use and disclosure practices regarding any personal information that you provide to us. The security of your personal information is important to us. While there is no such thing as "perfect security" on the Internet, we will take reasonable steps to help ensure the safety of your personal information. However, you understand and agree that such steps do not guarantee that the Website is invulnerable to all security breaches or immune from viruses, security threats or other vulnerabilities. We reserve the right to cooperate with local, state, provincial and national authorities in investigations of improper or unlawful activities and this may require the disclosure of your personal information.
PLEASE NOTE THAT THE TERMS ARE SUBJECT TO CHANGE BY ATLAS IN ITS SOLE DISCRETION AT ANY TIME.  When changes are made, Atlas will make a new copy of the Terms of Use available at the Website and any new Supplemental Terms will be made available from within, or through, the affected Service on the Website.  We will also update the “Last Updated” date at the top of these Terms of Use.  If we make any material changes, and you have registered to use the Services, we will also send an e-mail to you at the last e-mail address you provided to us pursuant to these Terms.  Any changes to these Terms will be effective immediately for new Users of the Website or Services and will be effective thirty (30) days after posting of notice of such changes on the Website for existing Users, provided that any material changes shall be effective for Users who have a registered account on the Website (each, a “Registered User”) upon the earlier of thirty (30) days after posting of notice of such changes on the Website or thirty (30) days after dispatch of an e-mail notice of such changes to Registered Users.  Atlas may require you to provide consent to the updated Terms in a specified manner before further use of the Website or the Services is permitted.  If you do not agree to any change(s) after receiving a notice of such change(s), you shall stop using the Website and/or the Services.  Otherwise, your continued use of the Website and/or Services constitutes your acceptance of such change(s).  PLEASE REGULARLY CHECK THE WEBSITE TO VIEW THE THEN-CURRENT TERMS. 

1.	Use of the Services and Atlas Materials.  The Application, the Software, the Widget, and the information and content available on the Website and in the Services (as these terms are defined below) (collectively, the “Atlas Materials”) are protected by copyright laws throughout the world.  Subject to these Terms, Atlas grants you a limited license to reproduce portions of the Atlas Materials for the sole purpose of using the Services for your personal or non-commercial purposes. Unless otherwise specified by Atlas in a separate license, your right to use any Atlas Materials that you access or download through the Website, the Application, or the Services is subject to the Terms. 
1.1	Application License.  Subject to your compliance with these Terms, Atlas grants you a limited non-exclusive, non-transferable, non-sublicensable, revocable license to download, install and use a copy of Application(s) on a single mobile device or computer that you own or control and to run such copy of the Application solely for your own personal use or internal business purposes.  Furthermore, with respect to any Application accessed through or downloaded from the Apple App Store  (an “App Store Sourced Application”), you will only use the App Store Sourced Application (i) on an Apple-branded product that runs the iOS (Apple’s proprietary operating system) and (ii) as permitted by the “Usage Rules” set forth in the Apple App Store Terms of Service.  
1.2	Software. Use of any software and associated documentation, other than the Application, that is made available via the Website or the Services (“Software”) is governed by the terms of the license agreement that accompanies or is included with the Software, or by the license agreement expressly stated on the Website page(s) accompanying the Software.  These license terms may be posted with the Software downloads or at the Website page where the Software can be accessed.  You shall not use, download or install any Software that is accompanied by or includes a license agreement unless you agree to the terms of such license agreement.  At no time will Atlas provide you with any tangible copy of our Software.  Atlas shall deliver access to the Software via electronic transfer or download and shall not use or deliver any tangible media in connection with the (a) delivery, installation, updating or problem resolution of any Software (including any new releases); or (b) delivery, correction or updating of documentation.  For the purposes of this section tangible media shall include, but not be limited to, any tape disk, compact disk, card, flash drive, or any other comparable physical medium.  Unless the accompanying license agreement expressly allows otherwise, any copying or redistribution of the Software is prohibited, including any copying or redistribution of the Software to any other server or location, or redistribution or use on a service bureau basis.  If there is any conflict between the Terms and the license agreement, the license agreement shall take precedence in relation to that Software (except as provided in the following sentence). If the Software is a pre-release version, then, notwithstanding anything to the contrary included within an accompanying license agreement, you are not permitted to use or otherwise rely on the Software for any commercial or production purposes.  If no license agreement accompanies use of the Software, use of the Software will be governed by the Terms.  Subject to your compliance with the Terms, Atlas grants you a non-assignable, non-transferable, non-sublicensable, revocable non-exclusive license to use the Software for the sole purpose of enabling you to use the Services in the manner permitted by the Terms.  Some Software may be offered under an open source license that we will make available to you. There may be provisions in the open source license that expressly override some of these terms.
1.3	Use of Widgets.  Our widgets are software tools that you may place on your website to permit your visitors to access our Website (each, a “Widget”). Widgets are only made available to subscribers of certain components of our Service. If you subscribe to a Service that includes the use of Widgets, then subject to your compliance with the Terms, we hereby grant you a non-exclusive, non-transferable, non-sublicensable, revocable license to use and display the Widget on your website for your own personal or internal business purposes.  You may not use the Widget for any other purpose without our prior written consent, and nothing in the Terms shall be deemed to grant you any right, title or interest in the Widget.  In addition, you may not:
(i)	Use the Widget (or any content displayed in connection with or through it) in any manner that would constitute an endorsement by us of any product, service, activity or brand contained on your website;
(ii)	Place the Widget on any website that includes content that is offensive, harassing, threatening, abusive, discriminatory, vulgar, pornographic, or otherwise inappropriate, as determined by us in our sole discretion; or
(iii)	Use the Widget in any manner that prevents the end users of your website from linking directly to the application page of our Website.
We reserve the right to discontinue providing any Widget at any time, or to direct you to cease displaying, or otherwise using, any Widget for any or no reason, without liability to you or any third party.
1.4	Updates.  You understand that the Website, the Application and the Services are evolving.  As a result, Atlas may require you to accept updates to the Website, the Application, or the Services that you have installed on your computer or mobile device.  You acknowledge and agree that Atlas may update the Website, the Application, and/or the Services with or without notifying you.  You may need to update third party software from time to time in order to receive the Services or use the Website, the Application and/or the Software.
1.5	Certain Restrictions.  The rights granted to you in these Terms are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, reproduce, distribute, host or otherwise commercially exploit the Website or any portion of the Website, including any Atlas Materials, (b) you shall not frame or utilize framing techniques to enclose any trademark, logo, or other Atlas Materials (including images, text, page layout or form) of Atlas; © you shall not use any metatarsi or other “hidden text” using Atlas’s name or trademarks; (d) you shall not modify, translate, adapt, merge, make derivative works of, disassemble, decompile, reverse compile or reverse engineer any part of the Atlas Materials except to the extent the foregoing restrictions are expressly prohibited by applicable law; (e) you shall not use any manual or automated software, devices or other processes (including but not limited to spiders, robots, scrapers, crawlers, avatars, data mining tools or the like) to “scrape” or download data from any web pages contained in the Website; (f) access the Atlas Materials in order to build a similar or competitive website, application or service; (g) except as expressly stated herein, no part of the Atlas Materials may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means; and (h) you shall not remove or destroy any copyright notices or other proprietary markings contained on or in the Atlas Materials. Any future release, update or other addition to the Atlas Materials shall be subject to these Terms.  Atlas, its suppliers and service providers reserve all rights not granted in the Terms.   Any unauthorized use of the Website, the Application, or the Services terminates the licenses granted by Atlas pursuant to the Terms.
1.6	Third Party Materials.   As a part of the Atlas Materials, you may have access to materials that are hosted by another party.  You agree that it is impossible for Atlas to monitor such materials and that you access these materials at your own risk.
1.7	Mobile Devices and Services. By accessing and using the Application, you acknowledge and agree that you may receive certain communications from the Services (such as SMS, MMS, text messages, mobile emails, or other electronic communications means, collectively “Mobile Communications”). Please note that by accessing and using the Application, you may incur fees from the provider or carrier of the mobile services that you use (“Carrier”) and you are solely responsible for the payment of such fees, including for text messages and data. When you use the Application, our Application pulls information from your local calendar, contacts, reminders and other functions and information on your mobile device and also pushes information you enter into the Application back to your calendar, as detailed in our privacy policy. You hereby authorize us and our Applications to take such actions and access your calendar, address book, tasks and related applications. 
2.	Registration.
2.1	Registering your Account.  In order to access certain features of the Website, the Application, and the Services you may be required to become a Registered User.  For purposes of these Terms, a “Registered User” is a User who has registered an account on the Website (“Account”), has a valid account on the social networking or other third party calendaring service (collectively, “SNS”) through which the User has connected to the Services (each such account, a “Third Party Account”),  or has an account with the applications provider for the User’s mobile device.
2.2	Access through an SNS.  If you access the Services through an SNS as part of the functionality of the Website and the Services, you may link your Account with Third Party Accounts, by allowing Atlas to access your Third Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third Party Account.  You represent that you are entitled to grant Atlas access to your Third Party Account (including, but not limited to, for use for the purposes described herein) without breach by you of any of the terms and conditions that govern your use of the applicable Third Party Account and without obligating Atlas to pay any fees or making Atlas subject to any usage limitations imposed by such third party service providers.  By granting Atlas access to any Third Party Accounts, you understand that Atlas will access, make available and store (if applicable) any Content that you have provided to and stored in your Third Party Account (“SNS Content”) so that it is available on and through the Website and Services via your Account Unless otherwise specified in the Terms, all SNS Content shall be considered to be Your Content (as defined in Section 4.1) for all purposes of the Terms.  Depending on the Third Party Accounts you choose and subject to the privacy settings that you have set in such Third Party Accounts, personally identifiable information that you post to your Third Party Accounts will be available on and through your Account on the Website and Services.  Please note that if a Third Party Account or associated service becomes unavailable or Atlas’s access to such Third Party Account is terminated by the third party service provider, then SNS Content will no longer be available on and through the Website and Services.  You have the ability to disable the connection between your Account and your Third Party Accounts at any time by accessing the “Settings” section of the Website or the Application.  PLEASE NOTE THAT YOUR RELATIONSHIP WITH THE THIRD PARTY SERVICE PROVIDERS ASSOCIATED WITH YOUR THIRD PARTY ACCOUNTS IS GOVERNED SOLELY BY YOUR AGREEMENT(S) WITH SUCH THIRD PARTY SERVICE PROVIDERS.  Atlas makes no effort to review any SNS Content for any purpose, including but not limited to, for accuracy, legality or non infringement and Atlas is not responsible for any SNS Content.
2.3	Atlas Direct Customer Access. If you are associated with an Atlas Direct customer, you may provide your login information to such customers’ systems to Atlas. You represent that you are entitled to disclose such login information to Atlas. By granting Atlas access to such account on the Atlas Direct customer system(s), you understand that Atlas may access, make available and store (if applicable) any Content that you have provided to and stored in your account with the Atlas Direct customer. Unless otherwise specified in the Terms, all such Content shall be considered to be Your Content (as defined in Section 4.1) for all purposes of the Terms.  Atlas makes no effort to review any such Content for any purpose, including but not limited to, for accuracy, legality or non infringement and Atlas is not responsible for any such Content.
2.4	Registration Data.  In registering for the Services, you agree to (1) provide true, accurate, current and complete information about yourself as prompted by the Services’ registration form (the “Registration Data”); and (2) maintain and promptly update the Registration Data to keep it true, accurate, current and complete.  You represent that you are (1) at least thirteen (13) years old; (2) of legal age to form a binding contract; and (3) not a person barred from using the Services under the laws of the United States, your place of residence or any other applicable jurisdiction. You agree that you shall monitor your Account to restrict use by minors, and you will accept full responsibility for any unauthorized use of the Atlas Materials or the Services by minors. If you provide any information that is untrue, inaccurate, not current or incomplete, or Atlas has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Atlas has the right to suspend or terminate your Account and refuse any and all current or future use of the Atlas Materials and/or the Services (or any portion thereof).  You agree not to create an Account using a false identity or information, or on behalf of someone other than yourself.  Atlas reserves the right to remove or reclaim any usernames at any time and for any reason, including but not limited to, claims by a third party that a username violates the third party’s rights.  You agree not to create an Account or use the Atlas Materials and/or the Services if you have been previously removed by Atlas, or if you have been previously banned from the Services.
2.5	Activities Under your Account.  You are responsible for all activities that occur under your Account.   You may not share your Account or password with anyone, and you agree to notify Atlas immediately of any unauthorized use of your password or any other breach of security. 
2.6	Necessary Equipment and Software.  You must provide all equipment and software necessary to connect to the Atlas Materials and the Services, including but not limited to, a mobile device that is suitable to connect with and use the Atlas Materials and the Services, in cases where the Services offer a mobile component.  You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Atlas Materials and the Services.
3.	Responsibility for Content.
3.1	Types of Content.  You acknowledge that all information, data, text, software, music, sound, photographs, graphics, video, messages, tags and/or other materials accessible through the Website, the Application or the Services, whether publicly posted or privately transmitted, including the Atlas Materials (“Content”), are the sole responsibility of the party from whom such Content originated.  This means that you, and not Atlas, are entirely responsible for all Content that you upload, post, e-mail, transmit or otherwise make available (“Make Available”) through the Services, the Application, or the Website (“Your Content”), and other Users of the Services, and not Atlas, are similarly responsible for all Content they Make Available through the Services, the Application, or the Website (“User Content”).
3.2	No Obligation to Pre-Screen Content.  You acknowledge that Atlas has no obligation to pre-screen Content (including, but not limited to, Your Content and User Content), although Atlas reserves the right in its sole discretion to pre-screen, refuse or remove any Content. In the event that Atlas pre-screens, refuses or removes any Content, you acknowledge that Atlas will do so for Atlas’s benefit, not yours.  Without limiting the foregoing, Atlas shall have the right to remove any Content that violates the Terms or is otherwise objectionable.
3.3	Storage.  Atlas has no responsibility or liability for the deletion or accuracy of any Content, including Your Content; the failure to store, transmit or receive transmission of Content; or the security, privacy, storage, or transmission of other communications originating with or involving use of the Services.  Certain Services may enable you to specify the level at which such Services restrict access to Your Content.  You are solely responsible for applying the appropriate level of access to Your Content.  If you do not choose, the system may default to its most permissive setting.  You agree that Atlas retains the right to create reasonable limits on Atlas’s use and storage of the Content, including Your Content, such as limits on file size, storage space, processing capacity, and similar limits described in the web pages accompanying the Services and as otherwise determined by Atlas in its sole discretion. 
4.	Ownership.
4.1	Atlas Materials.  Except with respect to Your Content and User Content, you agree that Atlas and its suppliers own all rights, title and interest in the Website, the Services, and the Atlas Materials   You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Website, the Services, or the Atlas Materials.
4.2	Trademarks. Atlas and other related graphics, logos, service marks and trade names used on the Website, in the Atlas Materials or in connection with the Services are the trademarks of Atlas and may not be used without permission in connection with any third party products or services.  Other trademarks, service marks and trade names that may appear on the Website, in the Atlas Materials or in connection with the Services are the property of their respective owners.
4.3	Other Content.  Except with respect to Your Content, you agree that you have no right or title in or to any Content that appears on or in the Website, the Application, the Software, or the Services.
4.4	Your Content.  Atlas does not claim ownership of Your Content.  However, when you as a User post or publish Your Content on or in the Website or the Services, you represent that you own and/or have a royalty-free, perpetual, irrevocable, worldwide, non-exclusive right (including any moral rights) and license to use, license, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, derive revenue or other remuneration from, and communicate to the public, perform and display Your Content (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or later developed, for the full term of any worldwide intellectual property right that may exist in Your Content.  
4.5	License to Your Content.  By submitting Your Content, which shall include your username, to the Website or the Services, you grant Atlas a fully paid, royalty-free, perpetual, irrevocable, worldwide, royalty-free, non-exclusive and fully sub licensable right (including any moral rights) and license to use, license, distribute, reproduce, modify, adapt, publicly perform, publicly display Your Content (in whole or in part) and/or to incorporate it in other works in any form, media or technology now known or later developed, for the full term of any worldwide intellectual property right, including moral rights, that may exist in Your Content. Before that scares you off, keep reading. We know these rights seem broad, but we are trying to cover all of the use cases for Your Content in one sentence – otherwise, this Agreement would be even longer. Don’t worry – this does not mean that all Content you provide us will be made publicly available. We  will use Your Content in accordance with the settings in which you submitted such Content, as detailed under our Privacy Policy. You also warrant that the holder of any worldwide intellectual property right, including moral rights, in Your Content, has completely and effectively waived all such rights and validly and irrevocably granted to you the right to grant the license stated above.  You agree that you, not the Atlas, are responsible for all of Your Content that you Make Available on or in the Website, or the Services, whether publicly posted or privately transmitted. IF YOU ARE AN ATLAS DIRECT SUBSCRIBER, THE COMPANY WITH WHICH YOU ARE AFFILIATED WILL BE THE OWNER OF ALL OF YOUR CONTENT THAT YOU MAKE AVAILABLE THROUGH THE APPLICATION OR SERVICE, AND WE MAY MAKE YOUR CONTENT AVAILABLE TO YOUR COMPANY AND ITS USERS. 
4.6	Username.  Notwithstanding anything contained herein to the contrary, by submitting Your Content to any forums, comments or any other area on the Website or the Services, you hereby expressly permit Atlas to identify you by your username (which may be a pseudonym) as the contributor of Your Content in any publication in any form, media or technology now known or later developed in connection with Your Content.
4.7	Your Account.  Notwithstanding anything to the contrary herein, you acknowledge and agree that you shall have no ownership or other property interest in your Account, and you further acknowledge and agree that all rights in and to your Account are and shall forever be owned by and inure to the benefit of Atlas.  
4.8	Feedback.  You agree that submission of any ideas, suggestions, documents, and/or proposals to Atlas through its suggestion, feedback, wiki, forum or similar pages (“Feedback”) is at your own risk and that Atlas has no obligations (including without limitation obligations of confidentiality) with respect to such Feedback.  You represent and warrant that you have all rights necessary to submit the Feedback.  You hereby grant to Atlas a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sub licensable right and license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all Feedback, and to sublicense the foregoing rights, in connection with the operation and maintenance of the Website, the Application, and the Services.
5.	User Conduct.
5.1	Commercial Activities.  You agree that you will not, under any circumstances (except to the extent expressly authorized by these Terms):
(a)	Reproduce, duplicate, copy, sell, trade, resell or exploit for any commercial purpose any portion of the Website, Services (including your Account), Atlas Materials, or access to or use of the Website, Services or Atlas Materials;
(b)	Upload, post, e-mail, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation;
©	Use the Website, Services, or Atlas Materials or any part thereof for any commercial purpose, including, but not limited to communicating or facilitating any commercial advertisement or solicitation; 
(d)	Engage in any chain letters, contests, junk email, pyramid schemes, spamming, surveys or other duplicative or unsolicited messages (commercial or otherwise); or
(e)	Market any goods or services for any business purposes.
For the avoidance of doubt, using the Application or the Services to make a reasonable number of appointment requests for bona fide appointments with other users will not violate any provision of this Section 5.1, as long as such requests are not made for the primary purpose of marketing or advertising goods and services. We reserve the right to suspend your use of the Services if we believe you are violating the provisions or spirit of this Section 5.1.
5.2	Unauthorized Use or Access. You agree that you will not, under any circumstances:
(a)	Interfere or attempt to interfere with the proper functioning of the Website, Services or Atlas Materials or connect to or use the Website, Services or Atlas Materials in any way not expressly permitted by the Terms, including, without limitation, through the use of viruses, cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, packet or IP spoofing, forged routing or electronic mail address information, or similar methods or technology;
(b)	Systematically retrieve data or other content from our Website, Services or Atlas Materials to create or compile, directly or indirectly, in single or multiple downloads, a collection, compilation, database, directory or the like, whether by manual methods, through the use of bots, crawlers, or spiders, or otherwise;
©	Use, display, mirror or frame the Website, Services or Atlas Materials, or any individual element within the Website, Services, or Atlas Materials, Atlas’s name, any Atlas trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without Atlas’s express written consent;
(d)	Intercept, examine or otherwise observe any proprietary communications protocol used by a client, a server or the Services, whether through the use of a network analyzer, packet sniffer or other device;
(e)	Make any automated use of the Website, Services, or Atlas Materials, or take any action that imposes or may impose (in Atlas’s sole discretion) an unreasonable or disproportionately large load on the infrastructure for the Website, Services or Atlas Materials;
(f)	Bypass any robot exclusion headers or other measures Atlas takes to restrict access to the Website, Services or Atlas Materials or use any software, technology or device to send content or messages, scrape, spider or crawl the Website, Services or Atlas Materials or harvest or manipulate data;
(g)	Use, facilitate, create, or maintain any unauthorized connection to the Website, Services or Atlas Materials, including, but not limited to: (a) any connection to any unauthorized server that emulates, or attempts to emulate, any part of the Website, Services or Atlas Materials; or (b) any connection using programs, tools or software not expressly approved by Atlas;
(h)	Reverse engineer, decompile, disassemble, decipher or otherwise attempt to derive the source code for any underlying software or other intellectual property used to provide the Website, Services or Atlas Materials, or to obtain any information from the Website, Services or Atlas Materials;
(i)	Upload, post, e-mail, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;
(j)	Solicit or attempt to solicit personal information from other users of the Website, Services or Atlas Materials;
(k)	Use our Website, Services or Atlas Materials to collect, harvest, transmit, distribute, post or submit any information concerning any other person or entity, including without limitation, photographs of others without their permission, personal contact information or credit, debit, calling card or account numbers; 
(l)	Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including, but not limited to, clear GIFs, 1x1 pixels, web bugs, cookies or other similar devices (sometimes referred to as “spyware,” “passive collection mechanisms” or “pcms”).
5.3	General.  In connection with your use of the Website, Services, and Atlas Materials, you shall not:
(a)	Make Available any Content that (i) is unlawful, tortious, defamatory, vulgar, obscene, libelous, or racially, ethnically or otherwise objectionable; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (iv) is violent or threatening or promotes violence or actions that are threatening to any other person; or (v) promotes illegal or harmful activities; 
(b)	Harm minors in any way;
©	Impersonate any person or entity, including, but not limited to, Atlas personnel, or falsely state or otherwise misrepresent your affiliation with a person or entity;
(d)	Make available any Content that you do not have a right to Make Available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under non-disclosure agreements);
(e)	Make Available any Content that infringes the rights of any person or entity, including without limitation, any patent, trademark, trade secret, copyright, privacy, publicity or other proprietary or contractual rights;
(f)	Intentionally or unintentionally violate any applicable local, state, national or international law or regulation, or any order of a court;
(g)	Register for more than one Account or register for an Account on behalf of an individual other than yourself; 
(h)	Stalk or otherwise harass any other user of our Website, Services or Atlas Materials; or
(i)	Advocate, encourage or assist any third party in doing any of the foregoing activities in this section.
6.	Investigations.  Atlas may, but is not obligated to, monitor or review the Services and Content at any time.  Without limiting the foregoing, Atlas shall have the right, in its sole discretion, to remove any of Your Content for any reason (or no reason), including if such Content violates the Terms or any applicable law.  Although Atlas does not generally monitor user activity occurring in connection with the Website, Services, Atlas Materials, or Content, if Atlas becomes aware of any possible violations by you of any provision of the Terms, Atlas reserves the right to investigate such violations, and Atlas may, at its sole discretion, immediately terminate your license to use the Website, Services, or Atlas Materials, or change, alter or remove Your Content, in whole or in part, without prior notice to you.
7.	Third Party Services.
7.1	Third-Party Websites & Ads.  The Website, Services, and Atlas Materials may contain links to third-party websites (“Third Party Websites”)  and advertisements for third parties (collectively, “Third Party Websites & Ads”).  When you click on a link to a Third Party Website or Ad, we will not warn you that you have left our Website and are subject to the terms and conditions (including privacy policies) of another website or destination.  Such Third Party Websites are not under the control of Atlas.  Atlas is not responsible for any Third Party Websites & Ads.  Atlas provides these Third Party Websites & Ads only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Websites & Ads, or their products or services.  You use all links in Third Party Websites & Ads at your own risk. When you leave our Website, our Terms and policies no longer govern. You should review applicable terms and policies, including privacy and data gathering practices, of any Third Party Websites, and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party. 
7.2	App Stores.  You acknowledge and agree that the availability of the Application and the Services is dependent on the third party from which you received the Application license, e.g., the Apple iPhone or Android app stores (“App Store”).  You acknowledge that these Terms are between you and Atlas and not with the App Store.  Atlas, not the App Store, is solely responsible for the Website, Services, and Application, the content thereof, maintenance, support services, and warranty therefor, and addressing any claims relating thereto (e.g. product liability, legal compliance, or intellectual property infringement).  In order to use the Application, you must have access to a wireless network, and you agree to pay all fees associated with such access.  You also agree to pay all fees (if any) charged by the App Store in connection with the Application or Services.  You agree to comply with, and your license to use the Application is conditioned upon your compliance with, all applicable third party terms of agreement (e.g., the App Store’s terms and policies) when using the Application and the Services.  You acknowledge that the App Store (and its subsidiaries) are third party beneficiaries of these Terms and will have the right to enforce them.
8.	Interactions with Other Users.
8.1	User Responsibility. You are solely responsible for your interactions with other Users of the Services and any other parties with whom you interact through the Services; provided, however, that Atlas reserves the right, but has no obligation, to intercede in such disputes.
8.2	Content Provided by Other Users. The Website, Services, and Atlas Materials may contain User Content provided by other Users. Atlas is not responsible for and does not control User Content. Atlas has no obligation to review or monitor, and does not approve, endorse or make any representations or warranties with respect to User Content. You use all User Content and interact with other Users at your own risk. Your interactions with other Users are solely between you and the other User and we are under no obligation to become involved. You agree that Atlas will not be responsible for any liability incurred as the result of such interactions.
8.3	Release. If you have a dispute with one or more Users, you release Atlas and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (collectively, the “Atlas Parties”) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes. If you are a California resident, you waive California Civil Code 1542, which says: “A general release does not extend to claims which the creditor does not now or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor.”
9.	Fees. We currently charge fees for the use of certain Applications and Services, although some of our Applications and/or Services are provided free of charge.
9.1	General Purpose of Terms: Sale of Service, not Software.  The purpose of the Terms is for you to secure access to the Services.  All fees set forth within and paid by you under the Terms shall be considered solely in furtherance of this purpose.  In no way are these fees paid considered payment for the sale, license, or use of the Software, and, furthermore, any use of the Software by you in furtherance of the Terms will be considered merely in support of the purpose of the Terms.
9.2	Payment.  You agree to pay all fees or charges to your Account in accordance with the fees, charges and billing terms in effect at the time a fee or charge is due and payable.  You must provide Atlas with a valid credit card (Visa, MasterCard, or any other issuer accepted by us) or PayPal account (“Payment Provider”), or purchase order information as a condition to signing up for the Services.  Your Payment Provider agreement governs your use of the designated credit card or PayPal account, and you must refer to that agreement and not the Terms to determine your rights and liabilities.  By providing Atlas with your credit card number or PayPal account and associated payment information, you agree that Atlas is authorized to immediately invoice your Account for all fees and charges due and payable to Atlas hereunder and that no additional notice or consent is required.  You agree to immediately notify Atlas of any change in your billing address or the credit card or PayPal account used for payment hereunder.  Atlas reserves the right at any time to change its prices and billing methods, either immediately upon posting on Atlas Materials (including on an App Store) or by e-mail delivery to you.
9.3	Service Subscription Fees. If you subscribe to a paid version of our Service, you will be responsible for payment of the applicable fee(s) for any Services (each, a “Service Subscription Fee”) at the time you create your Account and select your annual package (each, a “Service Commencement Date”). There are features of our Services that you can register for and use without paying a Subscription Fee. Except as set forth in the Terms, all fees for the Services are non-refundable.  No contract will exist between you and Atlas for the Services until Atlas accepts your order by a confirmatory e-mail, SNS/MMS message, or other appropriate means of communication.
9.4	Taxes.  Atlas’s fees are net of any applicable Sales Tax.  If any Services, or payments for any Services, under the Terms are subject to Sales Tax in any jurisdiction and you have not remitted the applicable Sales Tax to Atlas, you will be responsible for the payment of such Sales Tax and any related penalties or interest to the relevant tax authority, and you will indemnify Atlas for any liability or expense we may incur in connection with such Sales Taxes.  Upon our request, you will provide us with official receipts issued by the appropriate taxing authority, or other such evidence that you have paid all applicable taxes.  For purposes of this section, “Sales Tax” shall mean any sales or use tax, and any other tax measured by sales proceeds, that Atlas is permitted to pass to its customers, that is the functional equivalent of a sales tax where the applicable taxing jurisdiction does not otherwise impose a sales or use tax. 
9.5	Withholding Taxes.  You agree to make all payments of fees to Atlas free and clear of, and without reduction for, any withholding taxes.  Any such taxes imposed on payments of fees to Atlas will be your sole responsibility, and you will provide Atlas with official receipts issued by the appropriate taxing authority, or such other evidence as we may reasonably request, to establish that such taxes have been paid.   
9.6	Automatic Renewal.  Your subscription will continue indefinitely until terminated in accordance with the Terms.  After your initial subscription period, and again after any subsequent subscription period, your subscription will automatically commence on the first day following the end of such period (each a “Renewal Commencement Date”) and continue for an additional equivalent period, at Atlas’s then-current price for such subscription.  You agree that your Account will be subject to this automatic renewal feature unless you cancel your subscription at any time prior to the Renewal Commencement Date by logging into and going to the “Change/Cancel Membership” page of your “Account Settings” page.  If you do not wish your Account to renew automatically, or if you want to change or terminate your subscription, please log in and go to the “Change/Cancel Membership” page on your “Account Settings” page.  If you cancel your subscription, you may use your subscription until the end of your then-current subscription term; your subscription will not be renewed after your then-current term expires.  However, you will not be eligible for a prorated refund of any portion of the subscription fee paid for the then-current subscription period.  By subscribing, you authorize Atlas to charge your Payment Provider now, and again at the beginning of any subsequent subscription period.  Upon renewal of your subscription, if Atlas does not receive payment from your Payment Provider, (i) you agree to pay all amounts due on your Account upon demand, and/or (ii) you agree that Atlas may either terminate or suspend your subscription and continue to attempt to charge your Payment Provider until payment is received (upon receipt of payment,  your Account will be activated and for purposes of automatic renewal, your new subscription commitment period will begin as of the day payment was received).
9.7	Free Trials and Other Promotions.  Any free trial or other promotion that provides Registered User level access to the Services must be used within the specified time of the trial.  At the end of the trial period, your use of that Service will expire and any further use of the Service is prohibited unless you pay the applicable subscription fee.  If you are inadvertently charged for a subscription, please contact Atlas to have the charges reversed.
9.8	Disputes.  You must notify us in writing within seven (7) days after receiving your credit card statement, if you dispute any of our charges on that statement or such dispute will be deemed waived.  Billing disputes should be notified to the following address: Atlas Powered LLC, 820 Broadway #151, Santa Monica, CA 90401, USA._____________.
10.	Indemnification.  You agree to indemnify and hold Atlas and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (collectively, the “Atlas Parties” harmless from any losses, costs, liabilities and expenses (including reasonable attorneys’ fees) relating to or arising out of: (a) Your Content; (b) your use of, or inability to use, the Website,  the Application, or the Services; © your violation of the Terms; (d) your violation of any rights of another party, or (e) your violation of any applicable laws, rules or regulations.  Atlas reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Atlas in asserting any available defenses.  You agree that the provisions in this section will survive any termination of your Account or the Services.
11.	Disclaimer of Warranties.
11.1	AS IS.  YOU EXPRESSLY UNDERSTAND AND AGREE THAT TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOUR USE OF THE WEBSITE, THE APPLICATION, AND THE SERVICES IS AT YOUR SOLE RISK, AND THE WEBSITE, THE APPLICATION, AND THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITH ALL FAULTS.  ATLAS PARTIES EXPRESSLY DISCLAIM ALL WARRANTIES, REPRESENTATIONS, AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
(a)	THE ATLAS PARTIES MAKE NO WARRANTY, REPRESENTATION OR CONDITION THAT: (1) THE WEBSITE, THE APPLICATION, OR THE SERVICES WILL MEET YOUR REQUIREMENTS; (2) THE WEBSITE, THE APPLICATION, OR THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (3) THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE WEBSITE, THE APPLICATION, OR SERVICES WILL BE ACCURATE OR RELIABLE; OR (4) ANY ERRORS IN THE WEBSITE, THE SOFTWARE, THE APPLICATION OR THE SERVICES WILL BE CORRECTED.
(b)	ANY CONTENT OR ATLAS MATERIALS DOWNLOADED FROM OR OTHERWISE ACCESSED THROUGH THE WEBSITE, THE APPLICATION, OR THE SERVICES IS ACCESSED AT YOUR OWN RISK, AND YOU SHALL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY OR PERSON, INCLUDING, BUT NOT LIMITED TO, YOUR COMPUTER SYSTEM AND ANY DEVICE YOU USE TO ACCESS THE WEBSITE, THE APPLICATION, OR THE SERVICES, OR ANY OTHER LOSS THAT RESULTS FROM ACCESSING SUCH CONTENT.
©	THE SERVICES MAY BE SUBJECT TO DELAYS, CANCELLATIONS AND OTHER DISRUPTIONS.  ATLAS MAKES NO WARRANTY, REPRESENTATION OR CONDITION WITH RESPECT TO SERVICES, INCLUDING BUT NOT LIMITED TO, THE QUALITY, EFFECTIVENESS, REPUTATION AND OTHER CHARACTERISTICS OF SERVICES.
(d)	NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM ATLAS OR THROUGH THE WEBSITE OR THE ATLAS MATERIALS WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.
(e)	FROM TIME TO TIME, ATLAS MAY OFFER NEW “BETA” FEATURES OR TOOLS WITH WHICH ITS USERS MAY EXPERIMENT.  SUCH FEATURES OR TOOLS ARE OFFERED SOLELY FOR EXPERIMENTAL PURPOSES AND WITHOUT ANY WARRANTY OF ANY KIND, AND MAY BE MODIFIED OR DISCONTINUED AT ATLAS’S SOLE DISCRETION.  THE PROVISIONS OF THIS SECTION APPLY WITH FULL FORCE TO SUCH FEATURES OR TOOLS.
11.2	NO LIABILITY FOR CONDUCT OF THIRD PARTIES.  YOU ACKNOWLEDGE AND AGREE THAT THE ATLAS PARTIES ARE NOT LIABLE, AND YOU AGREE NOT TO SEEK TO HOLD THE ATLAS PARTIES LIABLE, FOR THE CONDUCT OF THIRD PARTIES, INCLUDING OPERATORS OF EXTERNAL SITES, AND THAT THE RISK OF INJURY FROM SUCH THIRD PARTIES RESTS ENTIRELY WITH YOU. 
12.	Limitation of Liability.
12.1	DISCLAIMER OF CERTAIN DAMAGES.  YOU UNDERSTAND AND AGREE THAT IN NO EVENT SHALL ATLAS PARTIES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE WEBSITE, THE APPLICATION, THE SOFTWARE, THE SERVICES OR THE SITE CONTENT, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES RESULTING FROM LOSS OF USE, DATA, OR PROFITS, WHETHER OR NOT ATLAS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, ON ANY THEORY OF LIABILITY, RESULTING FROM: (1) THE USE OR INABILITY TO USE THE WEBSITE, THE APPLICATION, OR THE SERVICES; (2) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED FOR TRANSACTIONS ENTERED INTO THROUGH THE WEBSITE, THE APPLICATION, OR THE SERVICES; (3) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (4) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE WEBSITE OR THE SERVICES; OR (5) ANY OTHER MATTER RELATED TO THE WEBSITE, THE APPLICATION, OR THE SERVICES, WHETHER BASED ON WARRANTY, COPYRIGHT, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY.
12.2	CAP ON LIABILITY.  UNDER NO CIRCUMSTANCES WILL ATLAS PARTIES BE LIABLE TO YOU FOR MORE THAN THE AMOUNT RECEIVED BY ATLAS AS A RESULT OF YOUR USE OF ATLAS MATERIALS IN THE SUBSCRIPTION PERIOD DURING WHICH YOU FIRST ASSERT A CLAIM.  IF YOU HAVE NOT PAID ATLAS ANY AMOUNTS IN THE SUBSCRIPTION PERIOD DURING WHICH YOU FIRST ASSERT ANY SUCH CLAIM, COMPANY’S SOLE AND EXCLUSIVE LIABILITY SHALL BE LIMITED TO FIFTY DOLLARS ($50). 
12.3	USER CONTENT.  THE ATLAS PARTIES ASSUME NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, MIS-DELIVERY OR FAILURE TO STORE ANY CONTENT (INCLUDING, BUT NOT LIMITED TO, YOUR CONTENT AND USER CONTENT), USER COMMUNICATIONS OR PERSONALIZATION SETTINGS.
12.4	Information Verification.  Atlas Parties may use various ways of verifying information that Users have provided.  However, none of those ways are perfect, and you agree that Atlas and its suppliers will have no liability to you arising from any incorrectly verified information.
12.5	BASIS OF THE BARGAIN.  THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN ATLAS AND YOU. 
13.	Procedure for Making Claims of Copyright Infringement.  It is Atlas’s policy to terminate membership privileges of any User who repeatedly infringes copyright upon prompt notification to Atlas by the copyright owner or the copyright owner’s legal agent.  Without limiting the foregoing, if you believe that your work has been copied and posted on the Website, or the Services in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed; (3) a description of the location on the Website or Services of the material that you claim is infringing; (4) your address, telephone number and e-mail address; (5) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; (6) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.  Contact information for Atlas’s Copyright Agent for notice of claims of copyright infringement is as follows: Copyright Agent ℅ Atlas Powered, LLC, 820 Broadway #151, Santa Monica, CA 90401, copyright@atlaspowered.com..
14.	Term and Termination.  
14.1	Term.  These Terms commence on the date when you accept them (as described in the preamble above) and remain in full force and effect while you use the Website, the Application, or any Services, unless terminated earlier in accordance with these Terms.
14.2	Prior Use.  Notwithstanding the foregoing, if you used the Website, the Application, or any Services prior to the date you accepted these Terms, you hereby acknowledge and agree that these Terms commenced on the date you first used the Website, the Application, or the Services (whichever is earlier) and will remain in full force and effect while you use the Website, the Application, or any other Services, unless earlier terminated in accordance with these terms.
14.3	Termination of Services.  If either party wants to terminate any Services provided by Atlas, such party may do so by notifying the other party at any time, at which point you will close your Account for all of the Services that you use. Any notice by you should be sent, in writing, to Atlas's address set forth below.  
14.4	Effect of Termination.  Termination of any Service includes removal of access to such Service and barring of further use of the Service.  Termination of all Services also includes deletion of your password and all related information, files and Content associated with or inside your Account (or any part thereof), including Your Content.  Upon termination of any Service, your right to use such Service will automatically terminate immediately.  You understand that any termination of Services may involve deletion of Your Content associated therewith from our live databases.  Atlas will not have any liability whatsoever to you for any suspension or termination, including for deletion of Your Content.  All provisions of these Terms which by their nature should survive, shall survive termination of Services, including without limitation, ownership provisions, warranty disclaimers, and limitation of liability.
15.	Remedies.
15.1	Violations.  If Atlas becomes aware of any possible violations by you of the Terms, Atlas reserves the right to investigate such violations.  If, as a result of the investigation, Atlas believes that criminal activity has occurred, Atlas reserves the right to refer the matter to, and to cooperate with, any and all applicable legal authorities.  Atlas is entitled, except to the extent prohibited by applicable law, to disclose any information or materials on the Website, the Application, or in the Services, including Your Content, in Atlas’s possession in connection with your use of the Website, the Application, or the Services, to (1) comply with applicable laws, legal process or governmental request; (2) enforce the Terms; (3) respond to any claims that Your Content violates the rights of third parties; (4) respond to your requests for customer service; or (5) protect the rights, property or personal safety of Atlas, its Users or the public, and all enforcement or other government officials, as Atlas in its sole discretion believes to be necessary or appropriate.
15.2	Breach.  In the event that Atlas determines, in its sole discretion, that you have breached any portion of these Terms, or have otherwise demonstrated conduct inappropriate for the Website, the Application, or the Services, Atlas reserves the right to:
(a)	Warn you via e-mail (to any e-mail address you have provided to Atlas) that you have violated these Terms;
(b)	Delete any of Your Content provided by you or your agent(s) to the Website, the Application, or the Services;
©	Discontinue your registration(s) with the Website and/or any Services or Atlas community;
(d)	Discontinue your subscription to any Services;
(e)	Notify and/or send Content to and/or fully cooperate with the proper law enforcement authorities for further action; and/or
(f)	Pursue any other action which Atlas deems to be appropriate.
15.3	No Subsequent Registration.  If your registration(s) with or ability to access the Website, the Application, or the Services, or any other Atlas community is discontinued by Atlas due to your violation of any portion of these Terms or for conduct otherwise inappropriate for the community, then you agree that you shall not attempt to re-register with or access the Website, the Application, the Software, the Services or any other Atlas community through use of a different member name or otherwise, and you acknowledge that you will not be entitled to receive a refund for fees related to those materials or Services to which  your access has been terminated.  In the event that you violate the immediately preceding sentence, Atlas reserves the right, in its sole discretion, to immediately take any or all of the actions set forth herein without any notice or warning to you.
16.	International Users. 
This Website can be accessed from countries around the world and may contain references to services and Content that are not available in your country.  These references do not imply that Atlas intends to announce such services or Content in your country.  The Website and Services are controlled and offered by Atlas from its facilities in the United States of America.  Atlas makes no representations that the Website or the Services are appropriate or available for use in other locations.  Those who access or use the Website or the Services from other jurisdictions do so at their own volition and are responsible for compliance with local law.
17.	General Provisions.
17.1	Electronic Communications.  The communications between you and Atlas use electronic means, whether you visit the Website or send Atlas e-mails, or whether Atlas posts notices on the Website or communicates with you via e-mail.  For contractual purposes, you (1) consent to receive communications from Atlas in an electronic form; and (2) agree that all terms and conditions, agreements, notices, disclosures, and other communications that Atlas provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing.  The foregoing does not affect your statutory rights.
17.2	Release.  You hereby release the Atlas Parties and their successors from claims, demands, any and all losses, damages, rights, and actions of any kind, including personal injuries, death, and property damage, that is either directly or indirectly related to or arises from any interactions with or conduct of other Website Users or third party websites of any kind arising in connection with or as a result of your these Terms or your use of the Website, the Application, or the Services.  If you are a California resident, you hereby waive California Civil Code Section 1542, which states, “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.
17.3	Assignment.  These Terms, and your rights and obligations hereunder, may not be assigned, subcontracted, delegated, or otherwise transferred by you without  Atlas’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void.
17.4	Force Majeure.  Atlas shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation facilities, fuel, energy, labor or materials.
17.5	Dispute Resolution.  If you believe that Atlas has not adhered to these Terms, please contact Atlas by emailing us at support@atlaspowered.com.  We will do our best to address your concerns.  If you feel that your complaint has been addressed incompletely, we invite you to let us know for further investigation.
17.6	Choice of Law and Venue.  This Agreement and any action related thereto will be governed and interpreted by and under the laws of the State of California, without giving effect to any conflict of laws principles that require the application of the law of a different state.   You hereby expressly consent to the personal jurisdiction and venue in the state and federal courts for the county in which Atlas’s principal place of business is located for any lawsuit filed against you by Atlas arising from or related to this Agreement.  The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.
17.7	Limitations Period.  YOU AND ATLAS AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THESE TERMS, THE WEBSITE, THE SERVICES OR THE CONTENT MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES.  OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
17.8	Arbitration. 
(a)	Any claim or dispute (excluding claims for injunctive or other equitable relief as set forth below) in connection with this Agreement where the total amount of the award sought is less than Five Thousand U.S. Dollars (US $5,000.00) may be resolved in a cost effective manner through binding non-appearance-based arbitration, at the option of the party seeking relief.  Such arbitration shall be initiated through an established alternative dispute resolution provider (“ADR Provider”) that offers arbitration as set forth in this section and under the rules of such ADR Provider, except to the extent such rules are in conflict with this Agreement.  The party demanding arbitration will propose an ADR Provider and the other party shall not unreasonably withhold consent to use such ADR Provider.  The ADR Provider and the parties must comply with the following rules: (1) the arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner shall be chosen by the party initiating the arbitration; (2) all arbitration proceedings shall be held in English; (3) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties; and (4) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.  Each party shall bear its own costs (including attorney fees) and disbursements arising out of the arbitration, and shall pay an equal share of the fees and costs of the ADR Provider.  Notwithstanding the foregoing, Atlas may seek injunctive or other equitable relief to protect its intellectual property rights in any court of competent jurisdiction.  Please note that the laws of the jurisdiction where you are located may be different from California law, including the laws governing what can legally be sold, bought, exported, offered or imported.  You shall always comply with all the international and domestic laws, ordinances, regulations and statutes that are applicable to your use of the Website and the Services.
(b)	Any other Dispute (including whether the claims asserted are arbitrable) shall be referred to and finally determined by arbitration in accordance with the JAMS Commercial Arbitration Rules (the “Rules”) and shall be administered by the Los Angeles office of JAMS (the “Administrator”). To the extent there is any conflict between the provisions set forth in this section and any procedural or other rules issued by the Administrator, this section will control. The location of the arbitration will be Los Angeles, CA. The Dispute(s) shall be submitted to a single arbitrator (“Arbitrator”) chosen by the parties or selected by the parties from a list of potential arbitrators provided by the Administrator. The Administrator shall provide such list to the parties 10 days after request by either party. Should the parties be unable to agree on a choice of arbitrator within 10 days after receipt of the list from the Administrator, then the Administrator will select the Arbitrator. The arbitral proceedings, and all pleadings and written evidence will be in the English language. Any written evidence originally in a language other than English will be submitted in English translation accompanied by the original or true copy thereof. The English language version will control. Each party shall bear its own attorney’s fees, costs, and disbursements arising out of the arbitration, and shall pay an equal share of the fees and costs of the Administrator and the Arbitrator; provided, however, the Arbitrator shall be authorized to determine whether a party is the prevailing party, and if so, to award to that prevailing party reimbursement for its reasonable attorneys’ fees, costs and disbursements (including, for example, expert witness fees and expenses, photocopy charges, travel expenses, etc.), and/or the fees and costs of the Administrator and the Arbitrator. The Arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The Arbitrator will not have authority to award damages in excess of the amount, or other than the types, allowed by Section 9 of this Agreement. Judgment on the award of the Arbitrators may be entered by any court of competent jurisdiction. The Arbitrator also shall be authorized to grant any temporary, preliminary or permanent equitable remedy or relief it deems just and equitable and within the scope of this Agreement, including, without limitation, an injunction or order for specific performance. The arbitration award shall be final and binding upon the parties without appeal or review except as permitted by California law or United States Federal law.
©	By using the Website, the Application, or the Services in any manner, you agree to the above arbitration provision.  In doing so, YOU GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend any claims between you and Atlas (except for matters that may be taken to small-claims court).  YOU ALSO GIVE UP YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION OR OTHER CLASS PROCEEDING.  Your rights will be determined by a NEUTRAL ARBITRATOR, NOT A JUDGE OR JURY.  You are entitled to a fair hearing before the arbitrator.  The arbitrator can grant any relief that a court can, but you should note that arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings.  Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons. 
17.9	Choice of Language.  It is the express wish of the parties that these Terms and all related documents have been drawn up in English.  C’est law volone expresse des parties que la presente convention ainsi que les documents qui s’y rattacent soient rediges en anglais.
17.10	Notice.  Where Atlas requires that you provide an e-mail address, you are responsible for providing Atlas with your most current e-mail address.  In the event that the last e-mail address you provided to Atlas is not valid, or for any reason is not capable of delivering to you any notices required/ permitted by these Terms, Atlas’s dispatch of the e-mail containing such notice will nonetheless constitute effective notice.  You may give notice to Atlas at the following address: support@atlaspowered.com. Such notice shall be deemed given when received by Atlas by letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail at the above address.
17.11	Waiver.  Any waiver or failure to enforce any provision of this Agreement on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.
17.12	Severability.  If any provision of these Terms is, for any reason, held to be invalid or unenforceable, the other provisions of these Terms will remain enforceable, and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.
17.13	Export Control.  You may not use, export, import, or transfer the Atlas Materials except as authorized by U.S. law, the laws of the jurisdiction in which you obtained the Atlas Materials, and any other applicable laws.  In particular, but without limitation, the Atlas Materials may not be exported or re-exported (a) into any United States embargoed countries; or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Department of Commerce’s Denied Person’s List or Entity List. By using the Atlas Materials, you represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You also will not use the Atlas Materials for any purpose prohibited by U.S. law, including the development, design, manufacture or production of missiles, nuclear, chemical or biological weapons.  You acknowledge and agree that products, services or technology provided by Atlas are subject to the export control laws and regulations of the United States.  You shall comply with these laws and regulations and shall not, without prior U.S. government authorization, export, re-export, or transfer Atlas products, services or technology, either directly or indirectly, to any country in violation of such laws and regulations.
17.14	Accessing and Download the Application from iTunes.  The following applies to any App Store Sourced Application: 
(a)	You acknowledge and agree that (i) these Terms are concluded between you and Atlas only, and not Apple, and (ii) Atlas, not Apple, is solely responsible for the App Store Sourced Application and content thereof. Your use of the App Store Sourced Application must comply with the App Store Terms of Service. 
(b)	You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App Store Sourced Application. 
©	In the event of any failure of the App Store Sourced Application to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App Store Sourced Application to you and to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App Store Sourced Application. As between Atlas and Apple, any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of Atlas. 
(d)	You and Atlas acknowledge that, as between Atlas and Apple, Apple is not responsible for addressing any claims you have or any claims of any third party relating to the App Store Sourced Application or your possession and use of the App Store Sourced Application, including, but not limited to: (i) product liability claims; (ii) any claim that the App Store Sourced Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.
(e)	You and Atlas acknowledge that, in the event of any third party claim that the App Store Sourced Application or your possession and use of that App Store Sourced Application infringes that third party’s intellectual property rights, as between Atlas and Apple, Atlas, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by these Terms. 
(f)	You and Atlas acknowledge and agree that Apple, and Apple’s subsidiaries, are third party beneficiaries of these Terms as related to your license of the App Store Sourced Application, and that, upon your acceptance of the terms and conditions of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms as related to your license of the App Store Sourced Application against you as a third party beneficiary thereof. 
(g)	Without limiting any other terms of these Terms, you must comply with all applicable third party terms of agreement when using the App Store Sourced Application.
17.15	Entire Agreement.  These Terms are the final, complete and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.
18.	International Provisions.  The following provisions shall apply only if you are located in the countries listed below.
18.1	United Kingdom.  A third party who is not a party to this Agreement has no right under the Contracts (Rights of Third Parties) Act 1999 to enforce any term of this Agreement, but this does not affect any right or remedy of such third party which exists or is available apart from that Act.
18.2	Germany.  Notwithstanding anything to the contrary in Section12, Atlas is also not liable for acts of simple negligence (unless they cause injuries to or death of any person), except when they are caused by a breach of any substantial contractual obligations (vertragswesentliche Pflichten).

		
		
		
		
		
		</div>
	</div>
</div>
	
	

	
	
	

	
<section>
	<div class="divider block4b">
		<a href="#" title="Download On App Store" class="apple_med" title="Download On App Store">
			<img src="<?=PATH?>/img/app-store-med.png" width="257" height="101" alt="Download On App Store" />
		</a>
		<a href="#" title="Download On Google Play" class="google_med" title="Download On Google Play">
			<img src="<?=PATH?>/img/google-med.png" width="257" height="101" alt="Download On Google Play" />
			<img class="coming" src="<?=PATH?>/img/coming-soon.png" width="125" height="21" alt="Coming Soon" />
		</a>
	</div>
</section>
</div>